const SET_PRESENTATION_TITLE = 'SET_PRESENTATION_TITLE';
const ADD_SLIDE = 'ADD_SLIDE';
const REMOVE_SLIDES = 'REMOVE_SLIDES';
const MOVE_SLIDE = 'MOVE_SLIDE';
const ADD_SLIDE_OBJECT = 'ADD_SLIDE_OBJECT';
const REMOVE_SLIDE_OBJECT = 'REMOVE_SLIDE_OBJECT';
const SET_OBJECT_POSITION_COORDINATES = 'SET_OBJECT_POSITION_COORDINATES';
const SET_OBJECT_POSITION_SIZE = 'SET_OBJECT_POSITION_SIZE';
const SET_TEXT_SIZE = 'SET_TEXT_SIZE';
const SET_FONT_FAMILY = 'SET_FONT_FAMILY';
const SET_TEXT_COLOR = 'SET_TEXT_COLOR';
const SET_TEXT_DESCRIPTION = 'SET_TEXT_DESCRIPTION';
const SET_SLIDE_BACKGROUND = 'SET_SLIDE_BACKGROUND';
const CHOOSE_SLIDE = 'CHOOSE_SLIDE';
const SET_SELECTED_OBJECTS = 'SET_SELECTED_OBJECTS';
const ADD_SELECTED_OBJECT = 'ADD_SELECTED_OBJECT';
const REMOVE_SELECTED_OBJECT = 'REMOVE_SELECTED_OBJECT';
const CLEAR_SELECTED_OBJECTS = 'CLEAR_SELECTED_OBJECTS';
const OPEN_PRESENTATION = 'OPEN_PRESENTATION';

export {
    SET_PRESENTATION_TITLE,
    ADD_SLIDE,
    REMOVE_SLIDES,
    MOVE_SLIDE,
    ADD_SLIDE_OBJECT,
    REMOVE_SLIDE_OBJECT,
    SET_OBJECT_POSITION_COORDINATES,
    SET_OBJECT_POSITION_SIZE,
    SET_TEXT_SIZE,
    SET_FONT_FAMILY,
    SET_TEXT_COLOR,
    SET_TEXT_DESCRIPTION,
    SET_SLIDE_BACKGROUND,
    CHOOSE_SLIDE,
    SET_SELECTED_OBJECTS,
    ADD_SELECTED_OBJECT,
    REMOVE_SELECTED_OBJECT,
    CLEAR_SELECTED_OBJECTS,
    OPEN_PRESENTATION,
}